### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by juanlabrador** [michaelkleinhenz/tk102b-server#3]
Thanks for the example, I don't have many 
knowledge about Node, but, It's possible emulate the send data in local machine? When open localhost:8844, in debug, get in server and inside of socket.on('data',...) is null. I need to testing it before to use the device. Thanks.  I was using Postman, pero I don't have idea as send data static like imei, coordinates, for to do testing. It's important.

**Comment by michaelkleinhenz** [comment]
Yes, that is possible. You neet to send a TCP message to the trackerPort with a single line message. You can do this using, for example, telnet. The format is specified in the regexp in `socket.on('data')` and the subsequent code that is retrieving the capture codes. You should also be able to find that format in the tracker manufacturer documentation.
